### ISSUE TITLE
cargo fmt breaks simdeez macro sometimes

### ISSUE THREAD

**Issue by BillyDM** [arduano/simdeez#40]
Running `cargo fmt` in a project will sometimes break the `simd_compiletime_generate!` and `simd_runtime_generate!` macros. When it does, rust says it cannot find any of the functions generated with the macro. For example,`cargo fmt` will break up long functions line by line for readability like this:
```rust
simd_compiletime_generate!(
fn smoothed_gain_4_simd(buf_1: &mut [f32], buf_2: &mut [f32], buf_3: &mut [f32], buf_4: &mut [f32], start_amp: f32, end_amp: f32) {
    // ...
});
```
becomes
```rust
simd_compiletime_generate!(
    fn smoothed_gain_4_simd(
        buf_1: &mut [f32],
        buf_2: &mut [f32],
        buf_3: &mut [f32],
        buf_4: &mut [f32],
        start_amp: f32,
        end_amp: f32,
    ) {
        // ...
    }
);
```

I found if I remove the comma after `end_amp: f32,` then it works again. However, running `cargo fmt` again adds the comma back.

**Comment by jackmott** [comment]
maybe we need to put the attribute that tells cargo fmt to leave it alone on there

**Comment by cisaacson** [comment]
I tried adding this attribute:

```
#[rustfmt::skip::macros(simd_runtime_generate)]
```

And it does work. However, it seems that since the trailing comma is legal Rust syntax as shown in the example above, can the macro be fixed to allow for this case?

**Comment by BillyDM** [comment]
I'll ask the Rust Community Discord to see if someone who is an expert on macros can help.

**Comment by BillyDM** [comment]
I also found this that may be useful. https://danielkeep.github.io/tlborm/book/pat-trailing-separators.html

**Comment by BillyDM** [comment]
The recent pull request fixed the issue for me. When can I expect the crates.io version to be updated with the fix?

**Comment by verpeteren** [comment]
I checked the commit logs and it seems that [this PR](https://github.com/arduano/simdeez/pull/44) fixed the trailing problem on  2020-08-29, just as @BillyDM mentioned on 2020-08-30.

I suggest that we close this issue.
