### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by cisaacson** [arduano/simdeez#61]
Does simdeez support Apple Silicon? The M1/M2 macs do have support for the AMD SIMD instruction set, just not `avx`.

**Comment by rdaum** [comment]
@cisaacson Apple Silicon is Aarch64 + NEON, and I believe the author is providing support here https://github.com/arduano/simdeez/tree/master/src/engines/neon

**Comment by verpeteren** [comment]
@rdaum is correct. It works on M1/M2 under neon.
You can see that the test pass for both `neon` and `scalar` when you run `cargo test`.

@arduano : You can close this issue.
